package com.yhw.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("yhw_org_info", "id", YhwOrgInfo.class);
		arp.addMapping("yhw_product", "id", YhwProduct.class);
		arp.addMapping("yhw_regist_info", "id", YhwRegistInfo.class);
		arp.addMapping("yhw_user", "id", YhwUser.class);
	}
}

