package com.yhw.common.model;

import com.yhw.common.model.base.BaseYhwOrgInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhwOrgInfo extends BaseYhwOrgInfo<YhwOrgInfo> {
	
}
