package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseYhwProduct<M extends BaseYhwProduct<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}
	
	public java.lang.String getCode() {
		return getStr("code");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPicture(java.lang.String picture) {
		set("picture", picture);
		return (M)this;
	}
	
	public java.lang.String getPicture() {
		return getStr("picture");
	}

	public M setBrand(java.lang.String brand) {
		set("brand", brand);
		return (M)this;
	}
	
	public java.lang.String getBrand() {
		return getStr("brand");
	}

	public M setCategory(java.lang.String category) {
		set("category", category);
		return (M)this;
	}
	
	public java.lang.String getCategory() {
		return getStr("category");
	}

	public M setSpecification(java.lang.String specification) {
		set("specification", specification);
		return (M)this;
	}
	
	public java.lang.String getSpecification() {
		return getStr("specification");
	}

	public M setOriginPalce(java.lang.String originPalce) {
		set("origin_palce", originPalce);
		return (M)this;
	}
	
	public java.lang.String getOriginPalce() {
		return getStr("origin_palce");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setAuditPerson(java.lang.String auditPerson) {
		set("audit_person", auditPerson);
		return (M)this;
	}
	
	public java.lang.String getAuditPerson() {
		return getStr("audit_person");
	}

	public M setAuditDate(java.util.Date auditDate) {
		set("audit_date", auditDate);
		return (M)this;
	}
	
	public java.util.Date getAuditDate() {
		return get("audit_date");
	}

	public M setProposedPriceRmb(java.lang.String proposedPriceRmb) {
		set("proposed_price_rmb", proposedPriceRmb);
		return (M)this;
	}
	
	public java.lang.String getProposedPriceRmb() {
		return getStr("proposed_price_rmb");
	}

	public M setProductRegistrationCertificate(java.lang.String productRegistrationCertificate) {
		set("product_registration_certificate", productRegistrationCertificate);
		return (M)this;
	}
	
	public java.lang.String getProductRegistrationCertificate() {
		return getStr("product_registration_certificate");
	}

	public M setAttorneyBook(java.lang.String attorneyBook) {
		set("attorney_book", attorneyBook);
		return (M)this;
	}
	
	public java.lang.String getAttorneyBook() {
		return getStr("attorney_book");
	}

	public M setOtherCertificates(java.lang.String otherCertificates) {
		set("other_certificates", otherCertificates);
		return (M)this;
	}
	
	public java.lang.String getOtherCertificates() {
		return getStr("other_certificates");
	}

	public M setPicture2(java.lang.String picture2) {
		set("picture2", picture2);
		return (M)this;
	}
	
	public java.lang.String getPicture2() {
		return getStr("picture2");
	}

	public M setPicture3(java.lang.String picture3) {
		set("picture3", picture3);
		return (M)this;
	}
	
	public java.lang.String getPicture3() {
		return getStr("picture3");
	}

	public M setPicture4(java.lang.String picture4) {
		set("picture4", picture4);
		return (M)this;
	}
	
	public java.lang.String getPicture4() {
		return getStr("picture4");
	}

	public M setPicture5(java.lang.String picture5) {
		set("picture5", picture5);
		return (M)this;
	}
	
	public java.lang.String getPicture5() {
		return getStr("picture5");
	}

	public M setPicture1(java.lang.String picture1) {
		set("picture1", picture1);
		return (M)this;
	}
	
	public java.lang.String getPicture1() {
		return getStr("picture1");
	}

	public M setIsMedicalInstrument(java.lang.String isMedicalInstrument) {
		set("is_medical_instrument", isMedicalInstrument);
		return (M)this;
	}
	
	public java.lang.String getIsMedicalInstrument() {
		return getStr("is_medical_instrument");
	}

	public M setProposedPriceHeight(java.lang.String proposedPriceHeight) {
		set("proposed_price_height", proposedPriceHeight);
		return (M)this;
	}
	
	public java.lang.String getProposedPriceHeight() {
		return getStr("proposed_price_height");
	}

	public M setBidderCode(java.lang.String bidderCode) {
		set("bidder_code", bidderCode);
		return (M)this;
	}
	
	public java.lang.String getBidderCode() {
		return getStr("bidder_code");
	}

}
