package com.demo.common.model;

import com.demo.common.model.base.BaseYhwProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhwProduct extends BaseYhwProduct<YhwProduct> {
	
}
