package com.demo.common.model;

import com.demo.common.model.base.BaseYhwRegistInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class YhwRegistInfo extends BaseYhwRegistInfo<YhwRegistInfo> {
	
}
