package com.yhw.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseYhwOrgInfo<M extends BaseYhwOrgInfo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setOrgCode(java.lang.String orgCode) {
		set("org_code", orgCode);
		return (M)this;
	}
	
	public java.lang.String getOrgCode() {
		return getStr("org_code");
	}

	public M setOrgName(java.lang.String orgName) {
		set("org_name", orgName);
		return (M)this;
	}
	
	public java.lang.String getOrgName() {
		return getStr("org_name");
	}

	public M setOrgRoleName(java.lang.String orgRoleName) {
		set("org_role_name", orgRoleName);
		return (M)this;
	}
	
	public java.lang.String getOrgRoleName() {
		return getStr("org_role_name");
	}

	public M setOrgProvince(java.lang.String orgProvince) {
		set("org_province", orgProvince);
		return (M)this;
	}
	
	public java.lang.String getOrgProvince() {
		return getStr("org_province");
	}

	public M setOrgCity(java.lang.String orgCity) {
		set("org_city", orgCity);
		return (M)this;
	}
	
	public java.lang.String getOrgCity() {
		return getStr("org_city");
	}

	public M setOrgTown(java.lang.String orgTown) {
		set("org_town", orgTown);
		return (M)this;
	}
	
	public java.lang.String getOrgTown() {
		return getStr("org_town");
	}

	public M setOrgAddress(java.lang.String orgAddress) {
		set("org_address", orgAddress);
		return (M)this;
	}
	
	public java.lang.String getOrgAddress() {
		return getStr("org_address");
	}

	public M setCorporation(java.lang.String corporation) {
		set("corporation", corporation);
		return (M)this;
	}
	
	public java.lang.String getCorporation() {
		return getStr("corporation");
	}

	public M setLinker(java.lang.String linker) {
		set("linker", linker);
		return (M)this;
	}
	
	public java.lang.String getLinker() {
		return getStr("linker");
	}

	public M setLinkTel(java.lang.String linkTel) {
		set("link_tel", linkTel);
		return (M)this;
	}
	
	public java.lang.String getLinkTel() {
		return getStr("link_tel");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setBusinesslLicenceAttr(java.lang.String businesslLicenceAttr) {
		set("businessL_licence_attr", businesslLicenceAttr);
		return (M)this;
	}
	
	public java.lang.String getBusinesslLicenceAttr() {
		return getStr("businessL_licence_attr");
	}

	public M setMedicalEquipBusinessLicenseAttr(java.lang.String medicalEquipBusinessLicenseAttr) {
		set("medical_equip_business_license_attr", medicalEquipBusinessLicenseAttr);
		return (M)this;
	}
	
	public java.lang.String getMedicalEquipBusinessLicenseAttr() {
		return getStr("medical_equip_business_license_attr");
	}

}
